dist: xenial
language: node_js
node_js: 'lts/*'
jobs:
  include:
    - script: yarn build && yarn test
    - script: yarn build && yarn docs && yarn docs:publish
      # if: branch = master AND type = push

