dist: xenial
language: node_js
node_js:
  - "10"
install:
  - yarn

jobs:
  include:
    - script: yarn build && yarn test
    - script: yarn build && yarn docs && yarn docs:publish
      # if: branch = master AND type = push

