language: node_js
node_js:
  - "10"
install:
  - yarn

stages:
  - pull request
  - master
jobs:
  include:
    - stage: pull request
      script: yarn build && yarn test
    - stage: master
      if: branch = master AND type = push
      script: yarn build && yarn docs && yarn docs:publish
