language: node_js
node_js:
  - "10"
install:
  - yarn

stages:
  - build
  - test
  - documentation
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
    - stage: documentation
      if: branch = master AND type = push
      script: yarn docs && yarn docs:publish
